export CC="clang"
export CXX="clang++"
export CFLAGS="-O3 -march=x86-64-v3 -flto=thin -fomit-frame-pointer"
export CXXFLAGS="$CFLAGS"
export LDFLAGS="-fuse-ld=mold -flto=thin"
export JOBS=$(nproc)
export ABUILD_GZIP="pigz -9"
export STRIP="strip --strip-unneeded"

# aarch64 override — set in CI matrix before sourcing this file
# export CFLAGS="-O3 -march=armv8.2-a+crypto -flto=thin -fomit-frame-pointer"
# export CXXFLAGS="$CFLAGS"
