0 libbz2-1.0
0 libcrypto3
0 libcurl4
0 libexpat1
0 libffi8
0 libjpeg62-turbo
0 liblzma5
0 libpcre2-8-0
0 libpng16-16
0 libpq5
0 libsqlite3-0
0 libssl3
0 libwebp7
0 libxml2
0 libzstd1
0 zlib1g
1 libtiff6
