#!/bin/sh
# mkpkginfo.sh <debian-control-file> <installed-size-bytes> [arch]
# Read Debian binary package control file, output APK .PKGINFO to stdout.
#
# Usage:
#   mkpkginfo.sh debian/control 1234567 x86_64
#   mkpkginfo.sh /tmp/work/control/control "$SIZE"
#
# Arch defaults to $(uname -m) if not given.

set -e

CONTROL="$1"
SIZE="$2"
ARCH="${3:-$(uname -m)}"

[ -f "$CONTROL" ] || { printf 'mkpkginfo: %s: not found\n' "$CONTROL" >&2; exit 1; }
[ -n "$SIZE" ]    || { printf 'mkpkginfo: size argument required\n' >&2; exit 1; }

# get <Field>: print value of a Debian control field (case-insensitive).
get() {
    grep -i "^$1:" "$CONTROL" | head -1 | sed 's/^[^:]*:[[:space:]]*//'
}

# deb_ver: strip Debian epoch, replace ~ with _, keep the rest.
# APK does not allow colons in versions; ~ is used for pre-releases.
# Example: 1:3.4.1-2  →  3.4.1-2
#          2.1~rc1-3  →  2.1_rc1-3
deb_ver() {
    printf '%s' "$1" | sed 's/^[0-9]*://; s/~/_/g'
}

# parse_deps: print one "depend = <name>" line per dependency.
# Handles: version constraints, arch qualifiers, alternative deps (| picks first).
# Input on stdin, one Debian dep per comma-separated token.
parse_deps() {
    tr ',' '\n' | while IFS= read -r dep; do
        # Take first alternative only
        dep="${dep%%|*}"
        # Strip version constraint: (>= 1.2)
        dep=$(printf '%s' "$dep" | sed 's/([^)]*)//g')
        # Strip arch qualifier: [amd64]
        dep=$(printf '%s' "$dep" | sed 's/\[[^]]*\]//g')
        # Trim whitespace
        dep=$(printf '%s' "$dep" | sed 's/^[[:space:]]*//; s/[[:space:]]*$//')
        [ -n "$dep" ] && printf 'depend = %s\n' "$dep"
    done
}

PKG=$(get Package)
VER=$(deb_ver "$(get Version)")
ARCH_FIELD=$(get Architecture)
DESC=$(get Description | sed 's/^[[:space:]]*//' | head -1)
URL=$(get Homepage)

[ -n "$PKG" ] || { printf 'mkpkginfo: no Package field in %s\n' "$CONTROL" >&2; exit 1; }
[ -n "$VER" ] || { printf 'mkpkginfo: no Version field in %s\n' "$CONTROL" >&2; exit 1; }

# Normalize arch: Debian uses amd64/arm64, APK uses x86_64/aarch64
case "$ARCH_FIELD" in
    amd64)  PKGARCH="x86_64"  ;;
    arm64)  PKGARCH="aarch64" ;;
    all)    PKGARCH="noarch"  ;;
    *)      PKGARCH="$ARCH"   ;;
esac
# If caller passed explicit arch, use it (handles cross-build detection)
[ "$ARCH" != "$(uname -m)" ] && PKGARCH="$ARCH"

printf '# Generated by silex-packages\n'
printf 'pkgname = %s\n'   "$PKG"
printf 'pkgver = %s-r0\n' "$VER"
printf 'arch = %s\n'      "$PKGARCH"
printf 'size = %s\n'      "$SIZE"
printf 'pkgdesc = %s\n'   "$DESC"
[ -n "$URL" ] && printf 'url = %s\n' "$URL"
printf 'builddate = %s\n' "$(date +%s)"
printf 'packager = silex-packages\n'

# Hard dependencies: Pre-Depends and Depends
for field in Pre-Depends Depends; do
    deps=$(get "$field")
    [ -n "$deps" ] && printf '%s\n' "$deps" | parse_deps
done
