#!/bin/sh
# mkpkginfo.sh <debian-control-file> <installed-size-bytes> [arch]
# Read a Debian binary package control file, output APK .PKGINFO to stdout.
#
# Translates Debian package metadata to APK .PKGINFO format.
# Only includes hard dependencies (Depends, Pre-Depends).
# Recommends/Suggests are NOT included since APK has no soft dependency mechanism.
# Handles multi-line dependencies (RFC 5322 continuation lines).
# Strips epochs (1:3.4.1 -> 3.4.1), normalises ~ to _ in versions.
# Arch defaults to $(uname -m) if not given.
#
# Environment:
#   DEP_OVERRIDES_FILE - path to config/dep-overrides.conf for manual dependency fixes
#   (default: ../config/dep-overrides.conf relative to script location)

set -e

CONTROL="$1"
SIZE="$2"
ARCH="${3:-$(uname -m)}"

[ -f "$CONTROL" ] || { printf 'mkpkginfo: %s: not found\n' "$CONTROL" >&2; exit 1; }
[ -n "$SIZE" ]    || { printf 'mkpkginfo: size argument required\n' >&2; exit 1; }

# get <Field>
# Print value of a Debian RFC 5322 control field (case-insensitive).
# Continuation lines (leading space/tab) are included, stripped of their
# leading whitespace, separated by newlines.  Stops at the next field or EOF.
get() {
    awk -v field="$1" '
        BEGIN { target = tolower(field); found = 0 }
        /^[^ \t]/ {
            if (found) { exit }
            key = $0; sub(/:.*$/, "", key)
            if (tolower(key) == target) {
                found = 1
                val = $0; sub(/^[^:]*:[[:space:]]*/, "", val)
                printf "%s", val
            }
        }
        found && /^[[:space:]]/ {
            line = $0; sub(/^[[:space:]]+/, "", line)
            printf "\n%s", line
        }
        END { if (found) print "" }
    ' "$CONTROL"
}

# deb_ver: strip Debian epoch, replace ~ with _
# APK versions cannot contain colons or tildes.
deb_ver() {
    printf '%s' "$1" | sed 's/^[0-9]*://; s/~/_/g'
}

# parse_deps <package-name>
# Read comma- or newline-separated Debian dependency list from stdin.
# Print one "depend = <name>" line per dependency.
# Handles: version constraints "(>= 1.2)", arch qualifiers "[amd64]",
# OR alternatives "a | b" (takes first available, skips virtual-only).
# Also handles architecture-specific dependencies via [arch] syntax.
parse_deps() {
    local pkgname="$1"
    local host_arch="${PKGARCH:-x86_64}"

    tr ',' '\n' | while IFS= read -r dep; do
        orig_dep="$dep"

        # Handle arch qualifiers: package [amd64] or package [!amd64]
        # If [!amd64], skip on amd64; if [amd64], only include on amd64
        if printf '%s' "$dep" | grep -q '\['; then
            arch_spec=$(printf '%s' "$dep" | sed 's/.*\[\([^]]*\)\].*/\1/')
            case "$arch_spec" in
                !$host_arch) ;; # Negated arch, skip on this arch
                !*) dep=$(printf '%s' "$dep" | sed 's/[[:space:]]*\[[^]]*\]//')  ;; # Negated other, include
                $host_arch) dep=$(printf '%s' "$dep" | sed 's/[[:space:]]*\[[^]]*\]//') ;; # Positive match
                *) continue ;; # Positive mismatch, skip
            esac
        fi

        # Handle OR alternatives: take first non-virtual package
        for alt in $(printf '%s' "$dep" | sed 's/[[:space:]]*|[[:space:]]/\n/g'); do
            alt=$(printf '%s' "$alt" | sed 's/([^)]*)//g; s/\[[^]]*\]//g; s/^[[:space:]]*//; s/[[:space:]]*$//')

            # Skip Debian build-system substitution variables (${shlibs:Depends} etc.)
            case "$alt" in '${'*) continue ;; esac

            # Skip empty after cleanup
            [ -n "$alt" ] || continue

            # Use this alternative
            dep="$alt"
            break
        done

        dep=$(printf '%s' "$dep" | sed 's/^[[:space:]]*//; s/[[:space:]]*$//')
        [ -n "$dep" ] && [ "$dep" != "$orig_dep" ] && printf 'depend = %s\n' "$dep"
    done
}

PKG=$(get Package)
VER=$(deb_ver "$(get Version)")
ARCH_FIELD=$(get Architecture)
DESC=$(get Description | head -1 | sed 's/^[[:space:]]*//')
URL=$(get Homepage)

[ -n "$PKG" ] || { printf 'mkpkginfo: no Package field in %s\n' "$CONTROL" >&2; exit 1; }
[ -n "$VER" ] || { printf 'mkpkginfo: no Version field in %s\n' "$CONTROL" >&2; exit 1; }

# Normalise arch: Debian amd64/arm64 -> APK x86_64/aarch64
case "$ARCH_FIELD" in
    amd64) PKGARCH="x86_64"  ;;
    arm64) PKGARCH="aarch64" ;;
    all)   PKGARCH="noarch"  ;;
    *)     PKGARCH="$ARCH"   ;;
esac

printf '# Generated by silex-packages\n'
printf 'pkgname = %s\n'   "$PKG"
printf 'pkgver = %s-r0\n' "$VER"
printf 'arch = %s\n'      "$PKGARCH"
printf 'size = %s\n'      "$SIZE"
printf 'pkgdesc = %s\n'   "$DESC"
[ -n "$URL" ] && printf 'url = %s\n' "$URL"
printf 'builddate = %s\n' "$(date +%s)"
printf 'packager = silex-packages\n'

# Hard dependencies: Pre-Depends then Depends
# Note: Recommends and Suggests are NOT included, as APK has no soft dependency mechanism.
# This differs from Debian but is necessary for APK compatibility.
for field in Pre-Depends Depends; do
    deps=$(get "$field")
    [ -n "$deps" ] && printf '%s\n' "$deps" | parse_deps "$PKG"
done

# Apply manual dependency overrides if config file exists
# Format: package:dependency (one per line, # for comments)
SCRIPT_DIR="$(cd "$(dirname "$0")" && pwd)"
REPO_ROOT="$(cd "$SCRIPT_DIR/.." && pwd)"
DEP_OVERRIDES_FILE="${DEP_OVERRIDES_FILE:-$REPO_ROOT/config/dep-overrides.conf}"
if [ -f "$DEP_OVERRIDES_FILE" ]; then
    grep "^${PKG}:" "$DEP_OVERRIDES_FILE" 2>/dev/null | while IFS=: read -r pkg dep; do
        [ -n "$dep" ] && printf 'depend = %s\n' "$dep"
    done || true
fi
